tags$div(
  h1("Instructions"),
  p("This tool is meant to provide a qucik look at data"),
  br(),
  h2("Download Data"),
  p(paste0("Data can be pulled annually. Data was last downloaded on : ", last_download_date)),
  br(),
  h2("Select Data"),
  p("Select data from CEDR,NWIS, or WQP. Narrow down the date range and parameter list"),
  br(),
  h2("Error Report"),
  p("Displays errors for selected data"),
  br(),
  h2("Grapth Data"),
  p("Displays graph for selected data"),
  br(),
  h2("Map Data"),
  p("Displays map for selected data"),
)
