---
title: "test_pad"
author: "Luke Vawter"
date: "10/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
project.dir <- rprojroot::find_rstudio_root_file()

print(project.dir)

active_path <- "data/ACTIVE/"

    #check if data exists
    if(file.exists(paste0(active_path, "active_data.csv"))){#("data/ACTIVE/active_data.csv")){
      print("file exists")
      

      active_data.df <- data.table::fread(paste0(active_path, "active_data.csv"),
                                    header = TRUE,
                                    data.table = FALSE)
    
    }else{print("file does not exist")}

 if(length(active_data.df) != 0){
   print("file has data")
   
       
    test_salinity.df <- active_data.df %>%
      filter(parameter == "salinity")
    
    test_din.df <- active_data.df %>%
      filter(parameter == "din")
    
    test_secchi.df <- active_data.df %>%
      filter(parameter == "secchi")
    
    test_po4.df <- active_data.df %>%
      filter(parameter == "po4")
    
    test_chla.df <- active_data.df %>%
      filter(parameter == "chla")
    
    test_pheo.df <- active_data.df %>%
      filter(parameter == "pheo")
    
    test_doc.df <- active_data.df %>%
      filter(parameter == "doc")
    
 pal <- colorNumeric(palette = c("yellow","purple"), domain = active_data.df$measurevalue)
 }



```

```{r}
  #assign active_data
  active_data.df <- data.table::fread(paste0(#project.dir, 
    active_path, "active_data.csv"),
                                      header = TRUE,
                                      data.table = FALSE)

if(length(active_data.df) >5){
  print("the data has values")
} else { "the data is empty"}

print(length(active_data.df))

library(plyr)
if(empty(active_data.df)){print("is empty")}
print(empty(active_data.df))

if(empty(active_data.df) == FALSE){print("there is data")}else{print("no good")}
print(empty(active_data.df) == FALSE)

chla.df <- active_data.df %>%
  filter(parameter == "chla")

if(empty(chla.df) == FALSE){print("there is chla data")}else{print("chla no good")}
print(empty(chla.df) == FALSE)

#checks if active_data.df has data
 if(empty(active_data.df) == FALSE){
   #check if chla.df has data
   if(empty(chla.df)== FALSE){
     Print("2 good")
   }}

if_empty <- function(dataframe) {
  empty(dataframe)== FALSE || is.na(empty(dataframe))
}

if(if_empty(active_data.df)){"print func not working"}else{print("func working")}
```

